import type { Car, CarCategory } from "./types";

export const cars: Car[] = [
  {
    id: "1",
    slug: "lamborghini-huracan-evo-spyder-blue",
    name: "Huracán EVO Spyder Blue",
    brand: "Lamborghini",
    category: "convertible",
    tagline: "2023 open-top V10",
    pricePerDay: 2499,
    image: "/cars/lamborghini-huracan-evo-spyder-blue.webp",
    specs: {
      horsepower: 610,
      acceleration: "0-100 km/h 3.5 s",
      drive: "AWD",
      seats: 2,
      transmission: "7-speed DCT",
      engine: "5.2L V10",
    },
    featured: true,
  },
  {
    id: "2",
    slug: "lamborghini-huracan-evo-spyder-black",
    name: "Huracán EVO Spyder Black",
    brand: "Lamborghini",
    category: "convertible",
    tagline: "2023 Nero open-top",
    pricePerDay: 2499,
    image: "/cars/lamborghini-huracan-evo-spyder-black.webp",
    specs: {
      horsepower: 610,
      acceleration: "0-100 km/h 3.5 s",
      drive: "AWD",
      seats: 2,
      transmission: "7-speed DCT",
      engine: "5.2L V10",
    },
  },
  {
    id: "3",
    slug: "lamborghini-huracan-evo-coupe-red",
    name: "Huracán EVO Coupe Red",
    brand: "Lamborghini",
    category: "supercar",
    tagline: "2022 Rosso V10 coupe",
    pricePerDay: 2199,
    image: "/cars/lamborghini-huracan-evo-coupe-red.webp",
    specs: {
      horsepower: 610,
      acceleration: "0-100 km/h 3.3 s",
      drive: "AWD",
      seats: 2,
      transmission: "7-speed DCT",
      engine: "5.2L V10",
    },
    featured: true,
  },
  {
    id: "4",
    slug: "lamborghini-urus-gray-2021",
    name: "Urus Gray",
    brand: "Lamborghini",
    category: "suv",
    tagline: "2021 Grigio super SUV",
    pricePerDay: 1999,
    image: "/cars/lamborghini-urus-gray-2021.webp",
    specs: {
      horsepower: 650,
      acceleration: "0-100 km/h 3.6 s",
      drive: "AWD",
      seats: 5,
      transmission: "8-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    noDeposit: true,
  },
  {
    id: "5",
    slug: "lamborghini-urus-silver-2022",
    name: "Urus Silver",
    brand: "Lamborghini",
    category: "suv",
    tagline: "2022 silver super SUV",
    pricePerDay: 1999,
    image: "/cars/lamborghini-urus-silver-2022.webp",
    specs: {
      horsepower: 650,
      acceleration: "0-100 km/h 3.6 s",
      drive: "AWD",
      seats: 5,
      transmission: "8-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    featured: true,
    noDeposit: true,
  },
  {
    id: "6",
    slug: "lamborghini-urus-black-2021",
    name: "Urus Black",
    brand: "Lamborghini",
    category: "suv",
    tagline: "2021 Nero super SUV",
    pricePerDay: 1999,
    image: "/cars/lamborghini-urus-black-2021.webp",
    specs: {
      horsepower: 650,
      acceleration: "0-100 km/h 3.6 s",
      drive: "AWD",
      seats: 5,
      transmission: "8-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    featured: true,
    noDeposit: true,
  },
  {
    id: "7",
    slug: "mercedes-g63-black-matte",
    name: "G63 AMG Black / Matte",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 satin black G-Wagen",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-black-matte.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    featured: true,
    noDeposit: true,
  },
  {
    id: "8",
    slug: "mercedes-g63-black",
    name: "G63 AMG Black",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 glossy Obsidian Black",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-black.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    noDeposit: true,
  },
  {
    id: "9",
    slug: "mercedes-g63-matte-black",
    name: "G63 AMG Matte Black",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 full matte wrap",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-matte-black.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    noDeposit: true,
  },
  {
    id: "10",
    slug: "mercedes-g63-gray",
    name: "G63 AMG Gray",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 Selenite Grey",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-gray.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    noDeposit: true,
  },
  {
    id: "11",
    slug: "mercedes-g63-gray-matte",
    name: "G63 AMG Gray / Matte",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 satin gray wrap",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-gray-matte.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    noDeposit: true,
  },
  {
    id: "12",
    slug: "mercedes-g63-white",
    name: "G63 AMG White",
    brand: "Mercedes-Benz",
    category: "suv",
    tagline: "2023 Polar White",
    pricePerDay: 1199,
    image: "/cars/mercedes-g63-white.webp",
    specs: {
      horsepower: 577,
      acceleration: "0-100 km/h 4.5 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    featured: true,
    noDeposit: true,
  },
  {
    id: "13",
    slug: "brabus-g-blue-carbon",
    name: "G-Class Blue / Black Carbon",
    brand: "Brabus",
    category: "suv",
    tagline: "2022 Widestar carbon",
    pricePerDay: 1799,
    image: "/cars/brabus-g-blue-carbon.webp",
    specs: {
      horsepower: 800,
      acceleration: "0-100 km/h 4.1 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.0L twin-turbo V8",
    },
    featured: true,
  },
  {
    id: "14",
    slug: "brabus-rocket-900-gray",
    name: "Rocket 900 Gray",
    brand: "Brabus",
    category: "suv",
    tagline: "2024 900 hp G-Wagen",
    pricePerDay: 1999,
    image: "/cars/brabus-rocket-900-gray.webp",
    specs: {
      horsepower: 900,
      acceleration: "0-100 km/h 3.7 s",
      drive: "AWD",
      seats: 5,
      transmission: "9-speed automatic",
      engine: "4.5L twin-turbo V8",
    },
    featured: true,
  },
  {
    id: "15",
    slug: "porsche-911-gt3-black-matte",
    name: "911 GT3 Black / Matte",
    brand: "Porsche",
    category: "sports",
    tagline: "2024 satin GT3",
    pricePerDay: 2499,
    image: "/cars/porsche-911-gt3-black-matte.webp",
    specs: {
      horsepower: 510,
      acceleration: "0-100 km/h 3.4 s",
      drive: "RWD",
      seats: 2,
      transmission: "7-speed PDK",
      engine: "4.0L naturally aspirated flat-6",
    },
  },
  {
    id: "16",
    slug: "ferrari-f8-tributo-red",
    name: "F8 Tributo",
    brand: "Ferrari",
    category: "supercar",
    tagline: "2022 Rosso Corsa",
    pricePerDay: 2399,
    image: "/cars/ferrari-f8-tributo-red.webp",
    specs: {
      horsepower: 720,
      acceleration: "0-100 km/h 2.9 s",
      drive: "RWD",
      seats: 2,
      transmission: "7-speed DCT",
      engine: "3.9L twin-turbo V8",
    },
    featured: true,
  },
  {
    id: "17",
    slug: "gmc-yukon-denali-black",
    name: "Yukon Denali",
    brand: "GMC",
    category: "suv",
    tagline: "2026 Onyx Black",
    pricePerDay: 899,
    image: "/cars/gmc-yukon-denali-black.webp",
    specs: {
      horsepower: 420,
      acceleration: "0-100 km/h 6.1 s",
      drive: "AWD",
      seats: 7,
      transmission: "10-speed automatic",
      engine: "6.2L V8",
    },
    noDeposit: true,
  },
];

export const categoryLabels: Record<CarCategory, string> = {
  supercar: "Supercar",
  sports: "Sports Car",
  suv: "Luxury SUV",
  sedan: "Sedan",
  convertible: "Convertible",
  electric: "Electric",
};

export function getCarBySlug(slug: string): Car | undefined {
  return cars.find((car) => car.slug === slug);
}

export function getFeaturedCars(): Car[] {
  return cars.filter((car) => car.featured);
}

export function getCarsByCategory(category: CarCategory): Car[] {
  return cars.filter((car) => car.category === category);
}

export function getCarsByBrand(brand: string): Car[] {
  return cars.filter(
    (car) => car.brand.toLowerCase() === brand.toLowerCase(),
  );
}

export function getAllBrands(): string[] {
  return [...new Set(cars.map((car) => car.brand))].sort();
}

export function getCarById(id: string): Car | undefined {
  return cars.find((car) => car.id === id);
}
